- NatDS.podspec
- NatDS.xcodeproj/project.pbxproj
- Sources/Colors/Colors.swift
- Tests/Colors/ColorsTests.swift
Add swiftlint to build phase and upgrade swift version to 5.
> Setup swiftlint

- .travis.yml
- NatDS.xcodeproj/xcshareddata/xcschemes/NatDS.xcscheme
> Add .travis.yml file

- .swiftlint.yml
- NatDS.xcodeproj/project.pbxproj
- Sources/Colors/Branding/ColorsNatura.swift
- Sources/Colors/Colors.swift
- Sources/Extensions/UIColor+hex.swift
- Tests/Colors/Branding/ColorsNaturaTests.swift
- Tests/Colors/ColorsTests.swift
- Tests/Extensions/UIColor+hexTests.swift
Add navigation drawer colors to Natura Themee.
> Navigation drawer colors

- NatDS.podspec
> Add resource to podspec

- Sources/Components/NavigationDrawer/NavigationDrawer+IndexMenu.swift
Turn NavigationDrawer.IndexMenu's initializer public
> Turn NavigationDrawer.IndexMenu's initializer public

- NatDS.podspec
- Sources/Components/NavigationDrawer/NavigationDrawer.swift
- Sources/Components/NavigationDrawer/NavigationDrawerItemCell.swift
Create public properties to set expanded/collapsed icons.
> Create public properties to set expanded/collapsed icon

- NatDS.podspec
- Sources/Components/NavigationDrawer/NavigationDrawerItemCell.swift
- Tests/ReferenceImages_64/NatDSTests.NavigationDrawerItemCellTests/test_disabledStateWithSubItems_hasDisabledSnapshotWithArrow@2x.png
- Tests/ReferenceImages_64/NatDSTests.NavigationDrawerItemCellTests/test_disabledStateWithoutSubItems_hasDisabledSnapshotWithoutArrow@2x.png
Fix navigation drawer alpha when state is disabled.
> Fix navigation drawer alpha when state is disabled

- NatDS.podspec
- Sources/Components/NavigationDrawer/NavigationDrawer.swift
Create method to reload data of the NavigationDrawer
> Create method to reload data of the NavigationDrawer

- NatDS.podspec
- NatDS.xcodeproj/project.pbxproj
- Sources/Components/Button/ContainedButton.swift
- Sources/DesignTokens/BoxShadow/BoxShadow.swift
- Sources/DesignTokens/Colors/Branding/ColorsNatura.swift
- Sources/DesignTokens/Colors/Colors.swift
- Sources/DesignTokens/Fonts/Branding/FontsNatura.swift
- Sources/DesignTokens/Fonts/Fonts.swift
- Tests/Components/Button/ContainedButtonTests.swift
- Tests/DesignTokens/Colors/Branding/ColorsNaturaTests.swift
- Tests/DesignTokens/Colors/ColorsTests.swift
- Tests/DesignTokens/Fonts/Branding/FontsNaturaTests.swift
- Tests/DesignTokens/Fonts/FontsTests.swift
- Tests/ReferenceImages_64/NatDSTests.ContainedButtonTests/test_init_hasValidSnapshot@2x.png
> Create Contained Button

- NatDS.podspec
- Sources/DesignTokens/Fonts/Branding/FontsNatura.swift
- Sources/DesignTokens/Fonts/Fonts.swift
- Tests/DesignTokens/Fonts/Branding/FontsNaturaTests.swift
- Tests/DesignTokens/Fonts/FontsTests.swift
> Create new font H5

- NatDS.podspec
Change podspec's author name and email
> Change podspec's author

- NatDS.podspec
- Sources/Components/NavigationDrawer/NavigationDrawerSubitemCell.swift
- Tests/ReferenceImages_64/NatDSTests.NavigationDrawerSubitemCellTests/test_disabledState_hasSnapshotWithAlphaText@2x.png
- Tests/ReferenceImages_64/NatDSTests.NavigationDrawerSubitemCellTests/test_normalState_hasNormalSnapshot@2x.png
- Tests/ReferenceImages_64/NatDSTests.NavigationDrawerSubitemCellTests/test_selectedState_hasSnapshotWithHighlightedView@2x.png
- Tests/ReferenceImages_64/NatDSTests.NavigationDrawerTests/test_cellForRowAt_whenItIsAnExpandedItem_hasValidSnapshot@2x.png
> Change subitem left margin

- NatDS.podspec
- SampleApp/Sources/Sample/Components/Divider/DividerViewController.swift
- SampleApp/Sources/Sample/Components/Field/TextFieldItemViewController.swift
- Sources/Components/Field/TextField.swift
- Sources/Components/Icons/IconView.swift
Moves the application of colors in IconView to the handleState function.
> Fix - IconView tint color in TextField component

- Sources/Components/Button/ContainedButton.swift
- Sources/Components/Button/FlatButton.swift
- Sources/Components/Button/Pulsable.swift
- Tests/Components/Button/PulsableTests.swift
- Tests/Components/Button/PulseLayerTests.swift
Fixed pulsable animation when click many times in button to create a softy animation.
> Pulsable animation

- NatDS.podspec
Update version to 0.0.19 on NatDS.podspec
> Update version to 0.0.19 on NatDS.podspec

- SampleApp/Sources/Sample/Design/Colors/ColorsItemViewController.swift
- Sources/Components/NavigationDrawer/NavigationDrawerSubitemCell.swift
- Sources/DesignTokens/Colors/Branding/ColorsNatura.swift
- Sources/DesignTokens/Colors/Colors.swift
- Tests/DesignTokens/Colors/Branding/ColorsNaturaTests.swift
- Tests/DesignTokens/Colors/ColorsTests.swift
- Tests/ReferenceImages_64/NatDSTests.NavigationDrawerSubitemCellTests/test_disabledState_hasSnapshotWithAlphaText@2x.png
- Tests/ReferenceImages_64/NatDSTests.NavigationDrawerSubitemCellTests/test_normalState_hasNormalSnapshot@2x.png
- Tests/ReferenceImages_64/NatDSTests.NavigationDrawerSubitemCellTests/test_selectedState_hasSnapshotWithHighlightedView@2x.png
- Tests/ReferenceImages_64/NatDSTests.NavigationDrawerTests/test_cellForRowAt_whenItIsAnExpandedItem_hasValidSnapshot@2x.png
Add surface and sufaceOn Colors
Add unit tests for surface and sufaceOn Colors
Update SampleApp
Design System reference:
https://xd.adobe.com/view/0eac63c5-4a15-451b-4cae-b840f4cace60-789d/screen/874b8c24-baf8-47f9-b4dd-36fce9ef0420/Color
> Add Surface and SurfaceOn Colors and update Sample App

- NatDS.podspec
> Bump podspec version

- fastlane/Fastfile
Removing a not necessary lane.
> Removing a not necessary lane.

- NatDS.xcodeproj/project.pbxproj
- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
- SampleApp/Sources/Sample/Design/Colors/ColorsViewController.swift
- SampleApp/Sources/Sample/Design/DesignSection.swift
- SampleApp/Sources/Sample/Design/Opacity/Cells/OpacityCell.swift
- SampleApp/Sources/Sample/Design/Opacity/OpacityViewController.swift
- SampleApp/Sources/Sample/Design/Size/Cells/SizeCell.swift
- SampleApp/Sources/Sample/Design/Spacing/Cells/SpacingCell.swift
- SampleApp/Sources/Sample/Design/Spacing/SpacingViewController.swift
- Sources/Core/DesignTokens/Opacities.swift
- Sources/Core/Theme/SupportedBrands/Avon/AvonOpacities.swift
- Sources/Core/Theme/SupportedBrands/Avon/AvonTheme.swift
- Sources/Core/Theme/SupportedBrands/Natura/NaturaOpacities.swift
- Sources/Core/Theme/SupportedBrands/Natura/NaturaTheme.swift
- Sources/Core/Theme/SupportedBrands/TheBodyShop/TheBodyShopOpacities.swift
- Sources/Core/Theme/SupportedBrands/TheBodyShop/TheBodyShopTheme.swift
- Sources/Core/Theme/Theme.swift
- Sources/Public/DesignTokens/DSOpacities.swift
- Tests/Core/SupportedBrands/Avon/AvonOpacities+Spec.swift
- Tests/Core/SupportedBrands/Avon/AvonThemeSpec.swift
- Tests/Core/SupportedBrands/Natura/NaturaOpacities+Spec.swift
- Tests/Core/SupportedBrands/Natura/NaturaThemeSpec.swift
- Tests/Core/SupportedBrands/TheBodyShop/TheBodyShopOpacities+Spec.swift
- Tests/Core/SupportedBrands/TheBodyShop/TheBodyShopTheme+Spec.swift
- Tests/Public/DesignTokens/DSOpacities+Spec.swift
- Adds DSOpacities to represent opacity token.
- Adds sample app demo for opacity
> Token opacity

- NatDS.podspec
- NatDS.xcodeproj/project.pbxproj
- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
- SampleApp/Sources/Supporting Files/Info.plist
- Supporting Files/Info.plist
> Bumping version 0.0.21

- SampleApp/Sources/Sample/Design/BorderRadius/BorderRadiusViewController.swift
- SampleApp/Sources/Sample/Design/BorderRadius/Cells/BorderRadiusCell.swift
- SampleApp/Sources/Sample/Design/Opacity/Cells/OpacityCell.swift
- SampleApp/Sources/Sample/Design/Size/Cells/SizeCell.swift
- SampleApp/Sources/Sample/Design/Size/SizeViewController.swift
- SampleApp/Sources/Sample/Design/Spacing/Cells/SpacingCell.swift
- SampleApp/Sources/Sample/Design/Spacing/SpacingViewController.swift
- SampleApp/Sources/Sample/Design/Tipography/Cells/TypographyCell.swift
- Updates sample app with new guide lines
> Updates sample app with new guide line for tokens.

- SampleApp/Sources/Sample/Design/Opacity/OpacityViewController.swift
- SampleApp/Sources/Sample/Design/Size/Cells/SizeCell.swift
- Changes border radius from size elements at sample app.
- Change order of elements at opacities list at sample app.
> Updates sample app: Opacities & Size

- SampleApp/Sources/Sample/Design/Opacity/OpacityViewController.swift
- Sources/Core/DesignTokens/Opacities.swift
- Sources/Core/Theme/SupportedBrands/Avon/AvonOpacities.swift
- Sources/Core/Theme/SupportedBrands/Natura/NaturaOpacities.swift
- Sources/Core/Theme/SupportedBrands/TheBodyShop/TheBodyShopOpacities.swift
- Sources/Public/DesignTokens/NatOpacities.swift
- Tests/Core/SupportedBrands/Avon/AvonOpacities+Spec.swift
- Tests/Core/SupportedBrands/Natura/NaturaOpacities+Spec.swift
- Tests/Core/SupportedBrands/TheBodyShop/TheBodyShopOpacities+Spec.swift
- Tests/Public/DesignTokens/NatOpacities+Spec.swift
- Adds more values to opacity token
> Adds more values to opacity token.

- NatDS.xcodeproj/project.pbxproj
- NatDS.xcodeproj/xcshareddata/xcschemes/NatDS.xcscheme
- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
- SampleApp/NatDS-SampleApp.xcodeproj/xcshareddata/xcschemes/NatDS-SampleApp.xcscheme
- Update settings to Xcode 11.4
> DSY-1006: Updates xcode settings to 11.4 (5.2)

- NatDS.podspec
- NatDS.xcodeproj/project.pbxproj
- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
> Bumps version to 0.2.0

- Sources/Core/ViewStyling/Button/ButtonOutlineStyle.swift
- Tests/Core/ViewStyle/Button/ButtonOutlinedStyle+Spec.swift
- Updates visual style of outlined button (color and kern).
> Updates visual style of outlined button

- Podfile
- Updates project to aways use a newer version from snapshot.
ps: also removes the warning of swift 4 from snapshot lib.
> [DSY-1078]: Updates snapshot version to 6.2.0

- NatDS.xcodeproj/project.pbxproj
- SampleApp/Sources/Sample/Components/Button/ButtonsItemViewController.swift
- SampleApp/Sources/Sample/Design/Elevation/Cells/ElevationCell.swift
- SampleApp/Sources/Sample/Design/Elevation/ElevationViewController.swift
- Sources/Core/DesignTokens/Elevation/ElevationAttributes.swift
- Sources/Core/DesignTokens/Elevation/Elevations.swift
- Sources/Core/Theme/SupportedBrands/Avon/AvonElevations.swift
- Sources/Core/Theme/SupportedBrands/Natura/NaturaElevations.swift
- Sources/Core/Theme/SupportedBrands/TheBodyShop/TheBodyShopElevations.swift
- Sources/Core/ViewStyling/Button/ButtonContainedStyle.swift
- Sources/Core/ViewStyling/Button/ButtonOutlineStyle.swift
- Sources/Core/ViewStyling/Button/ButtonStyle.swift
- Sources/Public/Components/Button/ContainedButton.swift
- Sources/Public/Components/Button/NatButton/NatButton+Style.swift
- Sources/Public/Components/Button/PulseContainerLayer.swift
- Sources/Public/DesignTokens/NatElevation.swift
- Tests/Core/SupportedBrands/Avon/AvonElevations+Spec.swift
- Tests/Core/SupportedBrands/Natura/NaturaElevations+Spec.swift
- Tests/Core/SupportedBrands/TheBodyShop/TheBodyShopElevations+Spec.swift
- Tests/Core/ViewStyle/Button/ButtonContainedStyle+Spec.swift
- Tests/Core/ViewStyle/Button/ButtonOutlinedStyle+Spec.swift
- Tests/Core/ViewStyle/Button/ButtonStyle+Spec.swift
- Tests/Public/DesignTokens/Colors/DynamicColorFactory+Spec.swift
- Tests/Public/DesignTokens/NatElevations+Spec.swift
- Creates style for Natbutton Stye. contained
- Updates elevation with value .none
- Deprecates ContainedButton.
- Fixes test typo: a expect -> an expected
> [DSY-935] - NatButton style  Contained

- NatDS.xcodeproj/project.pbxproj
- Sources/Public/Components/Button/Pulsable.swift
- Sources/Public/Components/Button/PulseContainerLayer.swift
- Tests/Public/Components/Button/Pusable/Pulsable+Spec.swift
- Tests/Public/Components/Button/Pusable/PulseContainerLayer+Spec.swift
- Changes animation color for pulse.
- Copy border radius from layer to animation container.
> [DSY-935] Fixes NatButton animation color and border radius

- NatDS.podspec
- NatDS.xcodeproj/project.pbxproj
- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
> Bump version to 1.0.0

- Sources/Public/Components/Button/NatButton/NatButton.swift
- Fixes typo on NatButton docs.
> Updates NatButton docs.

- Sources/Public/Components/Dialog/NatDialogController.swift
- Tests/Public/SnapShot/NatDialogController+Snapshot+Tests.swift
- Tests/ReferenceImages_64/NatDSTests.NatDialogControllerSnapshotTests/test_dialog_minimum_constraints_for_size_hasValidSnapshot@2x.png
- Tests/ReferenceImages_64/NatDSTests.NatDialogControllerSnapshotTests/test_dialog_minimum_contraints_for_size_hasValidSnapshot@2x.png
- Tests/ReferenceImages_64/NatDSTests.NatDialogControllerSnapshotTests/test_dialog_style_standard_hasValidSnapshot@2x.png
- Tests/ReferenceImages_64/NatDSTests.NatDialogControllerSnapshotTests/test_dialog_style_standard_with_vertical_buttons_hasValidSnapshot@2x.png
> feat: 🎸 [DSY-1104] add elevation to Dialog

- .typo-ci.yml
This PR brings little updates to Typo CI config.
> chore: ignore pbxproj files when looking for typos

- NatDS.podspec
- NatDS.xcodeproj/project.pbxproj
- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
> chore: 🤖 bumping version to 1.1.0

- Sources/Public/DesignTokens/DeprecatedWillBeRemoved/Colors.swift
- Sources/Public/DesignTokens/DeprecatedWillBeRemoved/Fonts.swift
- Adds "deprecated" tags to Colors and Fonts.
> [DSY-1179] refactor: 💡 Adds deprecated tag to Colors and Fonts

- NatDS.podspec
- NatDS.xcodeproj/project.pbxproj
- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
- Bumps version to 1.2.0.
- Update Sample app folder.
> chore: 🤖 Bumps version to 1.2.0 and organizes sample app files

- NatDS.podspec
- NatDS.xcodeproj/project.pbxproj
- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
> chore: 🤖 Bumps Version to 1.3.0

- NatDS.podspec
- NatDS.xcodeproj/project.pbxproj
- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
> chore: 🤖 Bumps version to 1.4.0

- Sources/Public/Components/Shortcut/NatShortcut.swift
> [DSY-942] docs: ✏️ Adds docs to shortcut component

- NatDS.podspec
- NatDS.xcodeproj/project.pbxproj
- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
> chore: 🤖 Bumps version to 1.5.0

- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
- SampleApp/Sources/Sample/Components/Button/ButtonsItemViewController.swift
- SampleApp/Sources/Sample/Components/Field/TextFieldItemViewController.swift
- SampleApp/Sources/Sample/Components/Iconography/Helper/IconCollectioViewCell.swift
- SampleApp/Sources/Sample/Components/Iconography/Helper/IconCollectionViewCell.swift
- SampleApp/Sources/Sample/Components/Iconography/IconographyItemViewController.swift
- SampleApp/Sources/Sample/Design/Colors/Cells/ColorsCell.swift
- SampleApp/Sources/Sample/Design/Colors/Cells/ColorsHeaderView.swift
- Sources/Public/Components/Field/TextField.swift
- Tests/Public/Components/Field/TextFieldTests.swift
- Update TextField to use multi brand tokens
- Update icons at sample app to support dark mode.
> [DSY-954] Update textfield

- .typo-ci.yml
This PR adds some words to Typo CI safelist.
> chore: add words to Typo CI safelist

- NatDS.podspec
- NatDS.xcodeproj/project.pbxproj
- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
> Version bump 1.6.0

- Sources/Public/Components/Field/TextField.swift
- Adds TextField label 2 lines limi.
> [DSY-1303] feat: 🎸 Adds TextField label 2 lines limit

- NatDS.podspec
- NatDS.xcodeproj/project.pbxproj
- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
> chore: 🤖 Version bump 1.7.0

- Makefile
- fastlane/Fastfile
- fastlane/README.md
- Removes old lanes from make file and fast file
> [DSY-1251] ci: 🎡 Removes old lanes from make file and fast file

- NatDS.podspec
- NatDS.xcodeproj/project.pbxproj
- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
> chore: 🤖 Bumps version to 1.8.0

- .typo-ci.yml
This PR proposes to:
- Add some words to Typo CI safelist;
- Remove "sut" (abbreviature of system under test) word.
> chore(typo-ci): update typo ci safelist

- NatDS.xcodeproj/project.pbxproj
- NatDSSnapShotTests/ExpansionPanel/ExpansionPanel+Snapshot+Tests.swift
- Sources/Core/DomainFunctions/GetComponentFromTheme.swift
- Sources/Core/Theme/SingleSourceOfTruth/DeprecatedWillBeRemoved/Theme/Theme.swift
- Sources/Core/ViewStyling/Button/ButtonStyle.swift
- Sources/Core/ViewStyling/Dialog/DialogStyle.swift
- Sources/Public/DesignTokens/NatFonts/NatFonts+TextStyle.swift
- Sources/Public/DesignTokens/NatFonts/NatFonts.swift
- Tests/Core/ViewStyle/Button/ButtonContainedStyle+Spec.swift
- Tests/Core/ViewStyle/Button/ButtonOutlinedStyle+Spec.swift
- Tests/Core/ViewStyle/Button/ButtonStyle+Spec.swift
- Tests/Core/ViewStyle/Button/ButtonTextStyle+Spec.swift
- Tests/Core/ViewStyle/Dialog/DialogStyle+Spec.swift
- Creates TextStyle to group elements of typography.
- Changes NatFonts  source to elements of new theme.
> [DSY-1369]refactor: 💡 Changes NatFonts source of values

- Sources/Public/Components/Shortcut/NatShortcut.swift
- Update Shortcut to has text alignment behaviour
Before:
After:
> [DSY-1419] refactor: 💡 Shortcut now has a new text alignment

- Sources/Core/DomainFunctions/DeprecatedWillBeRemoved/GetTheme.swift
- Sources/Core/DomainFunctions/DeprecatedWillBeRemoved/ValidateTheme.swift
> refactor: 💡 Removing old files

- LICENSE
Please include a summary of the changes and features that were added. Also include which JIRA task is this related to (name and link). List any dependencies that were added or removed for this change.
> chore(license): updates license to ISC

- NatDS.podspec
- NatDS.xcodeproj/project.pbxproj
- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
> chore: 🤖 Bumps version to 2.1.0

- Sources/Public/DesignSystem.swift
- Makes DesignSystem().currentTheme public
> refactor: 💡 makes DesginSystem().currentTheme public

- NatDS.podspec
- NatDS.xcodeproj/project.pbxproj
- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
> chore: 🤖 Bumps version 2.2.0

- NatDS.podspec
- NatDS.xcodeproj/project.pbxproj
- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
- Tests/Public/Components/Button/PulseLayerTests.swift
- docs/how-to-contribute.md
> chore: 🤖 Bumps version 2.3.0

- NatDSSnapShotTests/Bar/__Snapshots__/SearchBar+Snapshot+Tests/test_state_whenHasText_expectedCleanButtonIsVisible.1.png
- Sources/Public/Components/Bar/SearchBar.swift
- Applies tokens to search bar
> [DSY-1514] refactor: 💡 Applies tokens to search bar

- NatDS.podspec
- NatDS.xcodeproj/project.pbxproj
- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
> chore: 🤖 Bumps version to 2.3.1

- NatDS.podspec
- NatDS.xcodeproj/project.pbxproj
- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
> chore: 🤖 Bumps version to 2.4.0

- NatDS.podspec
- NatDS.xcodeproj/project.pbxproj
- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
> chore: bumps version to 2.5.0

- NatDS.podspec
- NatDS.xcodeproj/project.pbxproj
- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
> chore: bumps version to 2.6.0

- NatDS.podspec
> chore: updates .podspec

- NatDS.podspec
- NatDS.xcodeproj/project.pbxproj
- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
> chore: 🤖 Bumps version to 2.7.0

- NatDS-Swift.podspec
- iNatDS.podspec
> [DSY-1662] New pod

- README.md
- Updates how to install pod
- Update CI Status with bitrise
> [DSY-1662] docs: updates Readme with new pod and bitrise status

- NatDS.podspec
> [DSY-1671] chore: 🤖 Creates new NatDS.podspect

- NatDS-Swift.podspec
- NatDS.podspec
- NatDS.xcodeproj/project.pbxproj
- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
> Version bump 2.8.0

- Sources/Public/Components/IconButton/NatIconButton.swift
- Tests/Public/Components/IconButton/NatIconButton+Spec.swift
Please include a summary of the changes and features that were added. Also include which JIRA task is this related to (name and link). List any dependencies that were added or removed for this change.
> [DSY-255] Bugfix: disabled icon button behavior

- NatDS.podspec
- NatDS.xcodeproj/project.pbxproj
- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
> chore: bumps version to 2.8.1

- .cicd/build.sh
Adds script to automate documentation.
> ci: adds script to automate documentation

- NatDS.podspec
- NatDS.xcodeproj/project.pbxproj
- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
- Sources/Public/Components/IconButton/NatIconButton.swift
Bumps version to 2.9.0.
New features:
- Adds components documentation
- Adds new component: Progress Indicator Circular
> chore: bumps version to 2.9.0

- docs/documentation/index.html
> Updates index documentation

- SampleApp/Sources/ChooseBrand/ChooseBrandHeader.swift
> [DSY-1482] chore: 🤖 Adds build number

- Sources/Public/Components/Badge/NatBadge+Color.swift
- Sources/Public/Components/IconButton/NatIconButton+Sizes.swift
- Sources/Public/Components/ProgressIndicator/NatProgressIndicatorCircular+Size.swift
> style: 💄 Removes some white-spaces

- NatDS.podspec
- NatDS.xcodeproj/project.pbxproj
- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
- Bumps version to 2.10.0
- Updates TextField with password type
- Updates documentation
> chore: 🤖 Bumps version to 2.10.0

- docs/getting-started.md
- docs/how-to-contribute.md
Updates `how to contribute`  and `getting started` docs.
> docs: updates 'how to contribute' docs

- NatDS.podspec
- NatDS.xcodeproj/project.pbxproj
- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
> chore: bumps version to 2.10.1

- README.md
- docs/getting-started.md
- docs/how-to-contribute.md
- docs/using-icons.md
- Adds documentation for using `icon` tokens
- Minor fixes on current docs
> Adds icons docs

- .cicd/build.sh
- .cicd/copy-docs.sh
- .cicd/integration-test.sh
- .cicd/package.sh
- .cicd/unit-test.sh
This PR change the pipeline config to deploy branches beyond master.
This other docs will be available at natds-ios.natura.design/NAME_OF_THE_BRANCH/documentation/index.html
> chore: change pipeline to deploy docs on branches

- NatDS.podspec
- NatDS.xcodeproj/project.pbxproj
- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
> chore: bumps version to 2.11.0

- NatDSSnapShotTests/Button/NatButton+SnapShot+Tests.swift
- NatDSSnapShotTests/Button/__Snapshots__/NatButton+SnapShot+Tests/test_icon_left_side_hasValidSnapshot.2.txt
- NatDSSnapShotTests/Button/__Snapshots__/NatButton+SnapShot+Tests/test_icon_right_side_hasValidSnapshot.2.txt
- SampleApp/Sources/Sample/Components/Button/ButtonsItemViewController.swift
- Sources/Core/Helpers/AssetsHelper.swift
- Sources/Core/IconSource/IconsSource.swift
- Sources/Public/Components/Button/NatButton.swift
- Sources/Public/Components/Field/TextField.swift
- Sources/Public/Components/Icons/IconView.swift
- Tests/Public/Components/Button/NatButton+Specs.swift
- Updates NatButton to use NatDSIcons
> [DSY-1270] NatButton NatDSIcons

- NatDS.xcodeproj/project.pbxproj
- NatDSSnapShotTests/Shortcut/NatShortcut+Snapshot+Tests.swift
- NatDSSnapShotTests/Shortcut/__Snapshots__/NatShortcut+Snapshot+Tests/test_shortcut_style_contained_default_with_badge_hasValidSnapshot.1.png
- NatDSSnapShotTests/Shortcut/__Snapshots__/NatShortcut+Snapshot+Tests/test_shortcut_style_contained_primary_with_badge_hasValidSnapshot.1.png
- NatDSSnapShotTests/Shortcut/__Snapshots__/NatShortcut+Snapshot+Tests/test_shortcut_style_outlined_default_with_badge_hasValidSnapshot.1.png
- NatDSSnapShotTests/Shortcut/__Snapshots__/NatShortcut+Snapshot+Tests/test_shortcut_style_outlined_primary_with_badge_hasValidSnapshot.1.png
- SampleApp/Sources/Sample/Components/Shortcut/ShortcutItemViewController.swift
- Sources/Public/Components/Shortcut/NatShortcut.swift
- Sources/Public/Components/Shortcut/ShortcutView.swift
- Tests/Core/ViewStyle/Shortcut/ShortcutContainedStyle+Spec.swift
- Tests/Core/ViewStyle/Shortcut/ShortcutOutlinedStyle+Spec.swift
- Tests/Public/Components/Shortcut/NatShortcut+Spec.swift
- Add badge for shortcut components
- Minor refactor on shortcut for setting badge constraints
> [DSY-1736] feat: add badge configuration to shortcuts

- NatDSSnapShotTests/Shortcut/NatShortcut+Snapshot+Tests.swift
- Sources/Public/Components/Shortcut/NatShortcut.swift
- Tests/Public/Components/Shortcut/NatShortcut+Spec.swift
- Updated NatShortcut to use NatDSIcons
> [DSY-1761] Refactor NatShortcut to NatDSIcons

- Sources/Public/Components/IconButton/NatIconButton.swift
- Tests/Public/Components/IconButton/NatIconButton+Spec.swift
- Updates NatIconButton to use NatDSIcons
> [DSY-1755]  Updates NatIconButton to use NatDSIcons

- NatDS.podspec
- NatDS.xcodeproj/project.pbxproj
- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
> chore: bumps version to 2.12.0

- NatDS.xcodeproj/project.pbxproj
- Sources/Core/Helpers/AssetsPath.swift
- Sources/Public/Components/ExpansionPanel/ExpansionPanel.swift
- Sources/Public/Components/Field/TextField.swift
- Sources/Public/Components/Icons/IconView.swift
- Sources/Public/Components/NavigationDrawer/NavigationDrawerItemCell.swift
- Updates expansion panel to use NatDSIcons
> [DSY-1780] Updates expansion panel to use NatDSIcons

- NatDSSnapShotTests/AppBar/AppBar+Snapshot+Tests.swift
- NatDSSnapShotTests/AppBar/__Snapshots__/AppBar+Snapshot+Tests/test_appbar_style_default_rightbuttons_hasValidSnapshot.1.png
- SampleApp/Sources/Sample/Components/AppBar/AppBarDetailViewController.swift
- Sources/Public/Components/AppBar/UIBarButtonItem+Icon.swift
- Sources/Public/Components/Icons/IconView.swift
- Tests/Public/Components/AppBar/UIBarButtonItem+Icon+Spec.swift
- Tests/Public/Components/Icons/IconViewSpec.swift
Updates AppBar to use NatDSIcons
> [DSY-1756] Updates AppBar to use NatDSIcons

- NatDS.xcodeproj/project.pbxproj
- NatDSSnapShotTests/Badge/Badgeable+Snapshot+Tests.swift
- NatDSSnapShotTests/Badge/NatBadge+Dot+Snapshot+Tests.swift
- NatDSSnapShotTests/Badge/NatBadge+Standard+Snapshot+Tests.swift
- NatDSSnapShotTests/Badge/__Snapshots__/Badgeable+Snapshot+Tests/test_badge_style_dot_alert_count_1_hasValidSnapshot.1.png
- NatDSSnapShotTests/Badge/__Snapshots__/NatBadge+Dot+Snapshot+Tests/test_badge_style_dot_alert_hasValidSnapshot.1.png
- NatDSSnapShotTests/Badge/__Snapshots__/NatBadge+Dot+Snapshot+Tests/test_badge_style_standard_alert_count_100_hasValidSnapshot.1.png
- NatDSSnapShotTests/Badge/__Snapshots__/NatBadge+Standard+Snapshot+Tests/test_badge_style_standard_alert_count_100_hasValidSnapshot.1.png
- NatDSSnapShotTests/Badge/__Snapshots__/NatBadge+Standard+Snapshot+Tests/test_badge_style_standard_alert_count_1_hasValidSnapshot.1.png
- NatDSSnapShotTests/Badge/__Snapshots__/NatBadge+Standard+Snapshot+Tests/test_badge_style_standard_alert_count_50_hasValidSnapshot.1.png
- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
- SampleApp/Sources/Sample/Components/Badge/BadgeViewController.swift
- SampleApp/Sources/Sample/Components/Badge/BadgeableView.swift
- Sources/Public/Components/Badge/NatBadge+Color.swift
- Sources/Public/Components/Badge/NatBadge+Style.swift
- Sources/Public/Components/Badge/NatBadge.swift
- Sources/Public/Components/Badge/Protocol/Badgeable.swift
- Tests/Public/Components/Badge/NatBadge+Dot+Spec.swift
- Tests/Public/Components/Badge/NatBadge+Standard+Spec.swift
- Tests/Public/Components/Badge/Protocol/Badgeable+Spec.swift
- Creates a Dot variant for Badge
> [DSY-963] Creates a Dot variant for Badge

- docs/Getting started.md
- docs/How to use icons.md
- scripts/update_docs.sh
- Fix docs script to create a correct url for the documentation
- Update icons docs for `NatDSIcons 1.1.2`
> Docs: fix docs script + update docs

- NatDS.podspec
- Remove ttf icons reference from podspec file
> Chore: fix podspec to remove icons ttf reference

- NatDSSnapShotTests/NavigationDrawer/__Snapshots__/NavigationDrawerItemCell+Snapshot+Tests/test_setTagTextWithSubItems_withLargeTitle_hasSnapshotWithTag.1.png
- NatDSSnapShotTests/NavigationDrawer/__Snapshots__/NavigationDrawerItemCell+Snapshot+Tests/test_setTagText_withLargeTitle_hasSnapshotWithTag.1.png
- NatDSSnapShotTests/Tag/NatTag+Snapshot+Tests.swift
- NatDSSnapShotTests/Tag/__Snapshots__/NatTag+Snapshot+Tests/test_tag_style_default_alert_hasValidSnapshot.1.png
- NatDSSnapShotTests/Tag/__Snapshots__/NatTag+Snapshot+Tests/test_tag_style_left_alert_hasValidSnapshot.1.png
- NatDSSnapShotTests/Tag/__Snapshots__/NatTag+Snapshot+Tests/test_tag_style_right_alert_hasValidSnapshot.1.png
- SampleApp/Sources/Sample/Components/Tag/TagViewController.swift
- Sources/Public/Components/Tag/NatTag+Style.swift
- Sources/Public/Components/Tag/NatTag.swift
- Fix NatTag label padding
- Add new NatTag styles: left and right
> [DSY-1488] Refactor NatTag

- Sources/Public/Components/Field/Field.swift
- Sources/Public/Components/Field/TextField.swift
- Sources/Public/Components/IconButton/NatIconButton.swift
- Updates textfield to fit with password button
> [DSY-1727] refactor: 💡 Updates textfield to fit with password button

- NatDS.podspec
- NatDS.xcodeproj/project.pbxproj
- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
- Bumps version to 3.1.0
- New feature: Adds visibility button to password textfield
- Refactor NatTag
> chore: 🤖 bumps version to 3.1.0

- NatDS.xcodeproj/project.pbxproj
- NatDSSnapShotTests/Divider/Divider+Snapshot+Tests.swift
- NatDSSnapShotTests/Divider/__Snapshots__/Divider+Snapshot+Tests/test_divider_full_bleed_hasValidSnapshot.1.png
- NatDSSnapShotTests/Divider/__Snapshots__/Divider+Snapshot+Tests/test_divider_full_inset_hasValidSnapshot.1.png
- NatDSSnapShotTests/Divider/__Snapshots__/Divider+Snapshot+Tests/test_divider_full_middle_hasValidSnapshot.1.png
- NatDSSnapShotTests/ValueText/ValueTextHighlight+Snapshot+Tests.swift
- NatDSSnapShotTests/ValueText/__Snapshots__/ValueTextHighlight+Snapshot+Tests/test_init_hasValidSnapshot.1.png
- SampleApp/Sources/Sample/Components/Divider/DividerViewController.swift
- Sources/Public/Components/Divider/Divider+Style.swift
- Sources/Public/Components/Divider/Divider.swift
- Sources/Public/Components/ValueText/ValueTextHighlight.swift
- Tests/Public/Components/Divider/Divider+Spec.swift
- Tests/Public/Components/Divider/Divider+Styles+Spec.swift
- Adds variants: Full-bleed, Inset and Middle
> [DSY-1841] Adds Divider variants: Full-bleed, Inset and Middle

- NatDS.podspec
- NatDS.xcodeproj/project.pbxproj
- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
> chore: bump version to 3.2.0

- fastlane/Fastfile
Remove username from Fastfile to allow changing username at Bitrise.
> ci: remove username from fastfile

- NatDS.xcodeproj/project.pbxproj
- NatDSSnapShotTests/ProgressIndicator/ProgressIndicatorCircular+Snapshot+Tests.swift
- NatDSSnapShotTests/ProgressIndicator/__Snapshots__/ProgressIndicatorCircular+Snapshot+Tests/test_progress_indicator_circular_hasValidSnapshot.1.png
- NatDSSnapShotTests/ProgressIndicator/__Snapshots__/ProgressIndicatorCircular+Snapshot+Tests/test_progress_indicator_circular_hasValidSnapshot.1.txt
- NatDSSnapShotTests/ProgressIndicator/__Snapshots__/ProgressIndicatorCircular+Snapshot+Tests/test_progress_indicator_circular_hasValidSnapshot.2.txt
- NatDSSnapShotTests/ProgressIndicator/__Snapshots__/ProgressIndicatorCircular+Snapshot+Tests/test_progress_indicator_circular_useBackgroundLayer_hasValidSnapshot.1.txt
- SampleApp/Sources/Sample/Components/ProgressIndicator/ProgressIndicatorItemViewController.swift
- Sources/Public/Components/ProgressIndicator/NatProgressIndicatorCircular+Animation.swift
- Sources/Public/Components/ProgressIndicator/NatProgressIndicatorCircular+Constants.swift
- Sources/Public/Components/ProgressIndicator/NatProgressIndicatorCircular+Size.swift
- Sources/Public/Components/ProgressIndicator/NatProgressIndicatorCircular.swift
- Tests/Public/Components/ProgressIndicator/ProgressIndicatorCircular+Size+Spec.swift
- Tests/Public/Components/ProgressIndicator/ProgressIndicatorCircular+Spec.swift
- Updates animation
- Adds new tokens size for progress indicator
> [DSY-1895] Updates progress indicator circular

- Sources/Public/Components/Card/NatCard.swift
- Sources/Public/Components/Image/NatImage.swift
- Sources/Public/Components/ProgressIndicator/NatProgressIndicatorCircular.swift
- Tests/Public/Components/ProgressIndicator/ProgressIndicatorCircular+Spec.swift
- Changes progress indicator radius size
- Fixes progress indicator when dark mode is on
- Removes padding from card component
> refactor: 💡 Updates image, card and progress

- NatDS.podspec
- NatDS.xcodeproj/project.pbxproj
- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
> chore: 🤖 bumps version to 3.3.0

- scripts/bump_version.sh
- Fix script path to updated supporting files with new version
> Bugfix: fix path to supporting files with new version in the script

- CHANGELOG.md
- NatDSSnapShotTests/Info.plist
- SampleApp/Sources/Supporting Files/Info.plist
- Supporting Files/Info.plist
- Tests/Supporting Files/Info.plist
- scripts/bump_version.sh
> fix: Automate release pod trunk

- NatDS.xcodeproj/project.pbxproj
- NatDSSnapShotTests/ListItem/NatListItemCell+Snapshot+Tests.swift
- NatDSSnapShotTests/ListItem/__Snapshots__/NatListItemCell+Snapshot+Tests/test_listItem_fullbleedDivider_hasValidSnapshot.1.png
- NatDSSnapShotTests/ListItem/__Snapshots__/NatListItemCell+Snapshot+Tests/test_listItem_insetDivider_hasValidSnapshot.1.png
- NatDSSnapShotTests/ListItem/__Snapshots__/NatListItemCell+Snapshot+Tests/test_listItem_middleDivider_hasValidSnapshot.1.png
- NatDSSnapShotTests/ListItem/__Snapshots__/NatListItemCell+Snapshot+Tests/test_listItem_selected_hasValidSnapshot.1.png
- NatDSSnapShotTests/ListItem/__Snapshots__/NatListItemCell+Snapshot+Tests/test_listItem_unselected_hasValidSnapshot.1.png
- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
- SampleApp/Sources/Sample/Components/ComponentsSection.swift
- SampleApp/Sources/Sample/Components/ListItem/ListItemViewController.swift
- Sources/Public/Components/ListItem/NatListItem.swift
- Sources/Public/Components/SelectionControl/NatSelectionControl.swift
- Tests/Public/Components/List/NatListItem+Spec.swift
- Create `List Item` component
> [DSY-415] Create List Item component

- SampleApp/Sources/Sample/Components/Field/TextFieldItemViewController.swift
- SampleApp/Sources/Sample/Components/ListItem/ListItemViewController.swift
- Sources/Public/Components/Avatar/NatAvatar.swift
- Sources/Public/Components/SelectionControl/Selectors/NatCheckboxContainer.swift
- Sources/Public/Components/SelectionControl/Selectors/NatCheckboxControl.swift
- Fix warnings to allow radio button group release
> Fix warnings on radio button group

- NatDS.xcodeproj/project.pbxproj
- NatDSSnapShotTests/ListItem/NatListItemCell+Snapshot+Tests.swift
- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
- SampleApp/Sources/Sample/Components/ListItem/ListItemViewController.swift
- SampleApp/Sources/Sample/Components/ListItem/SampleCustomCell.swift
- Sources/Public/Components/ListItem/NatListItem+Feedback.swift
- Sources/Public/Components/ListItem/NatListItem.swift
Updates for component `NatListItemCell`:
- Allow subclassing to create custom cells
- Update with feedback style configuration
> Fix list item to allow subclassing

- NatDSSnapShotTests/AppBar/AppBar+Snapshot+Tests.swift
- NatDSSnapShotTests/IconButton/NatIconButton+Snapshot+Tests.swift
- NatDSSnapShotTests/Shortcut/NatShortcut+Snapshot+Tests.swift
- SampleApp/Sources/Sample/Components/AppBar/AppBarDetailViewController.swift
- SampleApp/Sources/Sample/Components/Shortcut/ShortcutItemViewController.swift
- Sources/Public/Components/AppBar/UIBarButtonItem+Icon.swift
- Sources/Public/Components/Badge/NatBadge.swift
- Sources/Public/Components/Badge/Protocol/Badgeable.swift
- Sources/Public/Components/IconButton/NatIconButton.swift
- Sources/Public/Components/Shortcut/NatShortcut.swift
- Sources/Public/Components/Shortcut/ShortcutView.swift
- Tests/Public/Components/IconButton/NatIconButton+Spec.swift
- Add new `configure(badge:)` methods to components that receive badge
- Deprecate old badge configurations to avoid breaking changes
> [DSY-2009] Refactor configure badge to components

- NatDSSnapShotTests/Tag/__Snapshots__/NatTag+Snapshot+Tests/test_tag_size_small_hasValidSnapshot.1.png
- NatDSSnapShotTests/Tag/__Snapshots__/NatTag+Snapshot+Tests/test_tag_size_standard_hasValidSnapshot.1.png
- NatDSSnapShotTests/Tag/__Snapshots__/NatTag+Snapshot+Tests/test_tag_style_left_alert_hasValidSnapshot.1.png
- NatDSSnapShotTests/Tag/__Snapshots__/NatTag+Snapshot+Tests/test_tag_style_right_alert_hasValidSnapshot.1.png
- Sources/Public/Components/Tag/NatTag.swift
- Fix visual for tags with positions `left` and `right`
- Update snapshot tests to match the fixed interface
> [DSY-2069] Fix visual for left and right tags

- SampleApp/Sources/Sample/Components/Tag/TagViewController.swift
- Remove unused code for `Tag` views in the Sample App
- Trigger new release with fixed pod trunk token
> Fix pod trunk and remove old tags

- Sources/Public/Components/SelectionControl/NatSelectionControl.swift
- Update `checkbox` label to accept more than one line
> Fix checkbox label

- Sources/Public/Components/Counter/NatCounter.swift
This PR add capability to set a value to NatCounter and new function to configure a closure to be notified when counter was changed
> feat: added capability to set value and listening changes to NatCounter

- README.md
- Add `Swift Package Manager` and `NatDSIcons` info at README
> Update docs at Readme

- NatDS.xcodeproj/project.pbxproj
- NatDSSnapShotTests/Dialog/NatDialogController+Snapshot+Tests.swift
- NatDSSnapShotTests/Dialog/__Snapshots__/NatDialogController+Snapshot+Tests/test_dialog_style_standard_with_divider_hasValidSnapshot.1.png
- SampleApp/Sources/Sample/Components/Dialog/DialogItemViewController.swift
- Sources/Core/ViewStyling/Dialog/DialogBodyView.swift
- Sources/Core/ViewStyling/Dialog/DialogFooterView.swift
- Sources/Core/ViewStyling/Dialog/DialogHeaderView.swift
- Sources/Core/ViewStyling/Dialog/DialogStyle.swift
- Sources/Public/Components/Dialog/Builders/NatDialogController+AlertStyleBuilder.swift
- Sources/Public/Components/Dialog/Builders/NatDialogController+StandardStyleBuilder.swift
- Sources/Public/Components/Dialog/Builders/Protocols/NatDialogBodyConfigurable.swift
- Sources/Public/Components/Dialog/Builders/Protocols/NatDialogBuilder.swift
- Sources/Public/Components/Dialog/Builders/Protocols/NatDialogCustomBodyConfigurable.swift
- Sources/Public/Components/Dialog/Builders/Protocols/NatDialogDismissableConfigurable.swift
- Sources/Public/Components/Dialog/Builders/Protocols/NatDialogDividerConfigurable.swift
- Sources/Public/Components/Dialog/Builders/Protocols/NatDialogTitleConfigurable.swift
- Sources/Public/Components/Dialog/DialogViewModel.swift
- Sources/Public/Components/Dialog/NatDialogController.swift
- Tests/Public/Components/Dialog/Builders/Protocols/NatDialogDividerConfigurable+Spec.swift
- Add `Divider` attribute to `Dialog` component
- Add more `Dialog` examples to the Sample App
- Update documentation for `Dialog` and its builders
> [DSY-2157] Update Dialog

- NatDS.podspec
- Fixes `Podspec` file to add font files as resources
> fix: update podspec

- NatDS.xcodeproj/project.pbxproj
- SampleApp/Sources/Sample/Components/Dialog/DialogItemViewController.swift
- Sources/Core/ViewStyling/Dialog/DialogFooterView.swift
- Sources/Public/Components/Dialog/Builders/NatDialogController+AlertStyleBuilder.swift
- Sources/Public/Components/Dialog/Builders/NatDialogController+StandardStyleBuilder.swift
- Sources/Public/Components/Dialog/Builders/Protocols/NatDialogCompletionHandlerConfigurable.swift
- Sources/Public/Components/Dialog/DialogViewModel.swift
- Sources/Public/Components/Dialog/NatDialogController.swift
- Add a completion handler for `Dialog` dismiss action
> [DSY-2423 add a completion handler for dialog dismiss action

- Sources/Public/Components/Field/TextField.swift
- Fix bug at `Text Field` with error feedback state
> [DSY-2427] Fix feedback state after editing textfield text

- Gemfile
- Makefile
- Sources/Public/Components/AppBar/UIViewController+Configure.swift
- Sources/Public/Components/ExpansionPanel/ExpansionPanel.swift
- fastlane/Fastfile
- fastlane/README.md
- scripts/bump_version.sh
- scripts/message_teams.json
- scripts/message_teams.sh
- Add script and json file for notification message at a Teams channel when new release is launched
> [DSY-2445] Automate release notifications at Teams

- NatDSSnapShotTests/Avatar/NatAvatar+Snapshots+Tests.swift
- SampleApp/Sources/Sample/Components/Avatar/AvatarItemViewController.swift
- SampleApp/Sources/Sample/Components/ProgressIndicator/ProgressIndicatorItemViewController.swift
- Sources/Core/Helpers/Fonts/Style/CustomFontStyle.swift
- Sources/Public/Animations/Pulsable.swift
- Sources/Public/Components/Avatar/NatAvatar.swift
- Sources/Public/Components/Field/TextField.swift
- Sources/Public/Components/Icons/IconView.swift
- Fix constraints (and warnings) at `Text Field` and `Avatar`
> [DSY-2476] Fix constraint warnings

- Sources/Public/Components/Image/NatImage.swift
- Remove default image from image component and fixes fallback configuration
> [DSY-2607] bugfix: remove default image from image component

- Sources/Public/Components/Card/NatCard.swift
- Update border radius tokens at component `Card` to make it customisable.
> [DSY-2550] Update border radius at component card

- Sources/Public/Components/Counter/NatCounter+Size.swift
- Update border radius tokens at component `Counter` to make it customisable.
> [DSY-2553] Update border radius at component counter

- Sources/Public/Components/Dialog/NatDialogController.swift
- Update border radius tokens at component `Dialog` to make it customisable.
> [DSY-2556] Update border radius at component dialog

- Sources/Public/Components/ExpansionPanel/ExpansionPanel.swift
- Update border radius tokens at component `Expansion Panel` to make it customisable.
> [DSY-2575] Update border radius at component expansion panel

- Makefile
- fastlane/Fastfile
- Add new lane to update profiles
- Add new rule at Makefile to profile update
> Update fastlane and makefile to update profiles

- Sources/Public/Components/ProgressIndicator/NatProgressIndicatorCircular.swift
- Update `Progress Indicator` animation to prevent it from stopping when view is removed
> [DSY-2660] Fix progress indicator constraints config to improve animation

- SampleApp/Sources/Sample/Components/Checkbox/CheckboxViewController.swift
- SampleApp/Sources/Sample/Components/Counter/CounterViewController.swift
- SampleApp/Sources/Sample/Components/ExpansionPanel/ExpansionPanelViewController.swift
- SampleApp/Sources/Sample/Components/IconButton/IconButtonItemViewController.swift
- SampleApp/Sources/Sample/Components/RadioButton/RadioButtonViewController.swift
- Sources/Public/Components/IconButton/NatIconButton.swift
- Sources/Public/Components/Shortcut/NatShortcut.swift
- Tests/Public/Components/AppBar/UINavigationController+Configure+Spec.swift
- Tests/Public/Components/IconButton/NatIconButton+Spec.swift
- Tests/Public/Components/Shortcut/NatShortcut+Spec.swift
- Update `Shortcut` action configuration method to prevent retain cycles
- Add action configuration examples at Sample App
> [DSY-2536] Prevent retain cycles

- SampleApp/Sources/Sample/Components/Dialog/DialogItemViewController.swift
Problem: Sample App crashing when touch inside a dialog
Fix selector on button action from dialog on sample app
> [DSY-2736] refactor: fix dialog screen sample app

- docs/How to contribute.md
- docs/Setup.md
- Update collaboration docs at Github (public).
> Update public docs for collaboration

- .github/PULL_REQUEST_TEMPLATE.md
- fastlane/Fastfile
- Update checklist at PR template
- Update `npm` installation to fix Bitrise issues
> chore: update PR template

- scripts/update_docs.sh
> Internal changes for docs automation

- Sources/Public/Components/Switch/NatSwitch.swift
> docs: update NatSwitch docs

- Sources/Public/Components/ExpansionPanel/ExpansionPanel.swift
> [DSY-1754] Remove buggy collapse animation

- NatDSSnapShotTests/TextField/TextField+Snapshot+Tests.swift
- SampleApp/Sources/Sample/Components/Field/TextFieldItemViewController.swift
- Sources/Public/Components/Field/TextField.swift
> [DSY-2735] feat: add method to configure text field icon button

- SampleApp/Sources/Sample/Components/AppBar/AppBarViewController.swift
- SampleApp/Sources/Sample/Components/ComponentsSection.swift
> [DSY-2646] [SampleApp] Moved searchBar cell from components list to inside AppBar cell

- Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AesopDark/Tokens/AesopDarkTokens+Color+Spec.swift
- Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AesopDark/Tokens/AesopDarkTokens+Typography+Spec.swift
- Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AesopLight/Tokens/AesopLightTokens+Color+Spec.swift
- Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AesopLight/Tokens/AesopLightTokens+Typography+Spec.swift
- Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AvonDark/Tokens/AvonDarkTokens+Color+Spec.swift
- Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AvonDark/Tokens/AvonDarkTokens+Typography+Spec.swift
- Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AvonLight/Tokens/AvonLightTokens+Color+Spec.swift
- Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/AvonLight/Tokens/AvonLightTokens+Typography+Spec.swift
- Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaDark/Tokens/NaturaDarkTokens+Typography+Spec.swift
- Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaLight/Tokens/NaturaLightTokens+Color+Spec.swift
- Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaLight/Tokens/NaturaLightTokens+Typography+Spec.swift
- Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/TheBodyShopDark/Tokens/TheBodyShopDarkTokens+Color+Spec.swift
- Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/TheBodyShopDark/Tokens/TheBodyShopDarkTokens+Typography+Spec.swift
- Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/TheBodyShopLight/Tokens/TheBodyShopLightTokens+Color+Spec.swift
- Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/TheBodyShopLight/Tokens/TheBodyShopLightTokens+Typography+Spec.swift
> Dsy 3141 new logo

- Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaDark/Tokens/NaturaDarkTokens+Typography+Spec.swift
- Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaLight/Tokens/NaturaLightTokens+Typography+Spec.swift
- [X fix: fixes a bug for the user, not a fix to a build script
> removing bodyFont

- Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaDark/Tokens/NaturaDarkTokens+Typography+Spec.swift
- Tests/Core/Theme/SingleSourceOfTruth/BrandsThemes/NaturaLight/Tokens/NaturaLightTokens+Typography+Spec.swift
> test-bitrise-pipe-cocoapods

- Tests/Supporting Files/TestingHelpers/Theme/StubTheme.swift
> fix: stubTokens missing string

- NatDS.podspec
> downgrade ios version from 11 to 11 at podspec

- Sources/Public/Components/Chip/NatChip.swift
> fiz natchip longpress error

- NatDS.xcodeproj/project.pbxproj
> bumping-macos-deployment-target-for-unit-tests

- Sources/Public/Components/Counter/NatCounter.swift
> change natcounter label to textfield

- Tests/Public/Components/Counter/NatCounter+Spec.swift
> fixing unit tests

- SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
- SampleApp/Sources/Sample/Components/Button/ButtonsItemViewController.swift
- Sources/Public/Components/Button/NatButton+Height.swift
- Sources/Public/Components/Button/NatButton.swift
> adding different sizes to button

- SampleApp/Sources/Sample/Components/Dialog/DialogItemViewController.swift
- Sources/Core/ViewStyling/Dialog/DialogFooterView.swift
- Sources/Public/Components/Dialog/Builders/NatDialogController+AlertStyleBuilder.swift
- Sources/Public/Components/Dialog/Builders/NatDialogController+StandardStyleBuilder.swift
- Sources/Public/Components/Dialog/DialogButtonConfiguration.swift
Adding switch themes in dialog component
> dialog with switch themes

- SampleApp/Sources/Sample/Components/AppBar/AppBarDataSource.swift
- SampleApp/Sources/Sample/Components/AppBar/AppBarDetailViewController.swift
- Sources/Public/Components/AppBar/AppBarColor.swift
- Sources/Public/Components/AppBar/AppBarContentType.swift
- Sources/Public/Components/AppBar/UINavigationController+Configure.swift
- Sources/Public/Components/AppBar/UIViewController+Configure.swift
> fixes for app bar review

- SampleApp/Sources/Sample/Components/Counter/CounterViewController.swift
- Sources/Public/Components/Counter/NatCounter.swift
Support for NatCounter: adding handle to resign keyboard
> adding handler to natcounter

- SampleApp/Sources/Sample/Components/Chip/ChipViewController.swift
- SampleApp/Sources/Sample/Components/ChipFilter/ChipFilterViewController.swift
- Sources/Public/Components/Chip/NatChip+Color.swift
- Sources/Public/Components/Chip/NatChip.swift
- Sources/Public/Components/ChipFilter/NatChipFilter+Color.swift
- Sources/Public/Components/ChipFilter/NatChipFilter.swift
- Sources/Public/Components/Shortcut/NatShortcut+Style.swift
> resolve natchip and natchipfilter switch themes

- Sources/Public/Components/NavigationDrawer/NavigationDrawer.swift
> Auto shrink section NavigationDrawer
