natura-cosmeticos/natds-ios

NatDS.podspec
Sources/Components/NavigationDrawer/NavigationDrawer.swift
Tests/Components/NavigationDrawer/Mock/NavigationDrawerDelegateMock.swift
Tests/Components/NavigationDrawer/NavigationDrawerTests.swift

Change navigation drawer to not call delegate when item/subitem is disabled

Change navigation drawer to not call delegate when item/subitem is disabled

---

Sources/Components/Button/ContainedButton.swift
Sources/Components/Button/FlatButton.swift
Tests/Components/Button/ContainedButtonTests.swift
Tests/Components/Button/FlatButtonTests.swift

Use `contentEdgeInsets` instead of `titleEdgeInsets` to make button size adapts to its title. This change affects only `FlatButton` and `ContainedButton`.

Fix size of buttons according to its titles

---

Sources/Components/Icons/Icon.swift
Tests/ReferenceImages_64/NatDSTests.IconTests/test_outlinedContentHealthy_hasValidSnapshot@2x.png
Tests/ReferenceImages_64/NatDSTests.IconTests/test_zOutlinedContentHealth_hasValidSnapshot@2x.png

Replace OutlinedContentHealthy with zOutlinedContentHealth icon

Replace OutlinedContentHealthy with zOutlinedContentHealth icon

---

Tests/.swiftlint.yml
Tests/Core/SupportedBrands/Avon/AvonSize+Spec.swift
Tests/Core/SupportedBrands/Avon/ColorPaletteDark/AvonColorPaletteDark+Feedback+Spec.swift
Tests/Core/SupportedBrands/Avon/ColorPaletteLight/AvonColorPaletteLight+Feedback+Spec.swift
Tests/Core/SupportedBrands/Natura/ColorPaletteDark/NaturaColorPaletteDark+Feedback+Spec.swift
Tests/Core/SupportedBrands/Natura/ColorPaletteLight/NaturaColorPaletteLight+Feedback+Spec.swift
Tests/Core/SupportedBrands/Natura/NaturaSize+Spec.swift
Tests/Core/SupportedBrands/TheBodyShop/ColorPaletteDark/TheBodyShopColorPaletteDark+Feedback+Spec.swift
Tests/Core/SupportedBrands/TheBodyShop/ColorPaletteLight/TheBodyShopColorPaletteLight+Feedback+Spec.swift
Tests/Core/SupportedBrands/TheBodyShop/ColorPaletteLight/TheBodyShopColorPaletteLight+Secondary+Spec.swift
Tests/Core/SupportedBrands/TheBodyShop/TheBodyShopSize+Spec.swift
Tests/Public/Components/Icons/IconTests.swift
Tests/Public/DSColorsSpec/DSColors+TBS+Spec.swift
Tests/Public/DesignSystem+Spec.swift
Tests/Public/DesignTokens/DSSizes+Spec.swift
Tests/Public/DesignTokens/DSSpacing+Spec.swift

- Creates lint specific for tests.
- Removes `swiftlint:disable` from the test code base.

Creates lint for tests

---

NatDS.xcodeproj/project.pbxproj
SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
SampleApp/Sources/Sample/Design/DesignSection.swift
SampleApp/Sources/Sample/Design/Elevation/Cells/ElevationCell.swift
SampleApp/Sources/Sample/Design/Elevation/ElevationViewController.swift
Sources/Core/DesignTokens/Elevation/ElevationAttributes.swift
Sources/Core/DesignTokens/Elevation/Elevations.swift
Sources/Core/Theme/SupportedBrands/Avon/AvonElevations.swift
Sources/Core/Theme/SupportedBrands/Avon/AvonTheme.swift
Sources/Core/Theme/SupportedBrands/Natura/NaturaElevations.swift
Sources/Core/Theme/SupportedBrands/Natura/NaturaTheme.swift
Sources/Core/Theme/SupportedBrands/TheBodyShop/TheBodyShopElevations.swift
Sources/Core/Theme/SupportedBrands/TheBodyShop/TheBodyShopTheme.swift
Sources/Core/Theme/Theme.swift
Sources/Core/ViewStyling/ViewStyling.swift
Sources/Public/DesignTokens/NatColors.swift
Sources/Public/DesignTokens/NatElevation.swift
Tests/Core/SupportedBrands/Avon/AvonElevations+Spec.swift
Tests/Core/SupportedBrands/Avon/AvonThemeSpec.swift
Tests/Core/SupportedBrands/Natura/NaturaElevations+Spec.swift
Tests/Core/SupportedBrands/Natura/NaturaThemeSpec.swift
Tests/Core/SupportedBrands/TheBodyShop/TheBodyShopElevations+Spec.swift
Tests/Core/SupportedBrands/TheBodyShop/TheBodyShopTheme+Spec.swift
Tests/Core/ViewStyling/ViewStyling+Spec.swift
Tests/Public/DesignTokens/NatElevations+Spec.swift
Tests/Supporting Files/TestingHelpers/ElevationAttributes+Equitable.swift

- Adds `NatElevations`, to apply shadow elements to a view layer making a visual elevation effect.
- Adds visual representation of `NatElevations` at sample app.

Elevation token

---

SampleApp/Sources/Sample/Design/Elevation/Cells/ElevationCell.swift
Sources/Core/ViewStyling/ViewStyle.swift
Sources/Public/Components/Button/NatButton/NatButton.swift
Sources/Public/DesignTokens/NatElevation.swift
Tests/Core/ViewStyle/ViewStyle+Spec.swift
Tests/Public/DesignTokens/NatElevations+Spec.swift

Changes parameters names from `onView:` or `onButton:` to just `on:`

Changes parameters names from `onView:` or `onButton:` to just `on:`

---

NatDS.xcodeproj/project.pbxproj
SampleApp/Sources/Sample/Components/Button/ButtonsItemViewController.swift
Sources/Core/ViewStyling/Button/ButtonContainedStyle.swift
Sources/Core/ViewStyling/Button/ButtonOutlineStyle.swift
Sources/Core/ViewStyling/Button/ButtonStyle.swift
Sources/Core/ViewStyling/Button/ButtonTextStyle.swift
Sources/Public/Components/Button/FlatButton.swift
Sources/Public/Components/Button/NatButton/NatButton+Style.swift
Sources/Public/Components/Button/NatButton/NatButton.swift
Tests/Core/ViewStyle/Button/ButtonContainedStyle+Spec.swift
Tests/Core/ViewStyle/Button/ButtonOutlinedStyle+Spec.swift
Tests/Core/ViewStyle/Button/ButtonStyle+Spec.swift
Tests/Core/ViewStyle/Button/ButtonTextStyle+Spec.swift

- Creates NatButton text style
- NatButton does accept nil for title, it need to have some value.
- Updates NatButton documentation
- Deprecates FlatButton

[DSY-936]: Creates NatButton text style

---

NatDS.xcodeproj/project.pbxproj
Sources/Core/ViewStyling/Button/ButtonContainedStyle.swift
Sources/Core/ViewStyling/Button/ButtonStyle.swift
Sources/Public/Components/Button/NatButton/NatButton+EdgeInsets.swift
Sources/Public/Components/Button/NatButton/NatButton+Height.swift
Tests/Core/ViewStyle/Button/ButtonContainedStyle+Spec.swift
Tests/Core/ViewStyle/Button/ButtonOutlinedStyle+Spec.swift
Tests/Core/ViewStyle/Button/ButtonStyle+Spec.swift
Tests/Core/ViewStyle/Button/ButtonTextStyle+Spec.swift
Tests/Public/Components/Button/NatButton+EdgeInsets+Spec.swift
Tests/ReferenceImages_64/NatDSTests.NatDialogControllerSnapshotTests/test_dialog_style_standard_hasValidSnapshot@2x.png
Tests/ReferenceImages_64/NatDSTests.NatDialogControllerSnapshotTests/test_dialog_style_standard_with_vertical_buttons_hasValidSnapshot@2x.png

- Adds pre set values to NatButton content edge insets (small, medium, large)
- Design changes: Colors for NatButton state `Disable`, to better for accessibility.

[DSY-412] Updates Natbutton: Colors for disabled + EdgeInsets.

---

.typo-ci.yml

This PR adds the word `enum` to Typo CI safelist

chore: add "enum" to safelist to .typo-ci.yml

---

.typo-ci.yml

This PR adds "sut" word to Typo CI safelist

chore: add "sut" to Typo CI safelist

---

SampleApp/Sources/Sample/Components/ComponentsSection.swift
Sources/Public/DesignTokens/NatFonts.swift

- Adds bold to NatFonts.font.
ps: source of truth has changed and will be updated in next few weeks, it doesn't affect the NatFonts's contract. For now only NatFonts.font will gain access to `bold`.

[DSY-1274] feat: 🎸 Adds bold to NatFonts.font

---

NatDSSnapShotTests/IconButton/__Snapshots__/NatIconButton+Snapshot+Tests/test_style_standard_color_default_pressed_hasValidSnapshot.1.txt
NatDSSnapShotTests/IconButton/__Snapshots__/NatIconButton+Snapshot+Tests/test_style_standard_color_default_tapped_hasValidSnapshot.2.txt
NatDSSnapShotTests/IconButton/__Snapshots__/NatIconButton+Snapshot+Tests/test_style_standard_color_primary_pressed_hasValidSnapshot.1.txt
NatDSSnapShotTests/IconButton/__Snapshots__/NatIconButton+Snapshot+Tests/test_style_standard_color_primary_tapped_hasValidSnapshot.2.txt
Sources/Core/Animations/Pulsable.swift

- Sets pulse animation below elements like Badge, Tag...
Antes:
Depois:

[DSY-1457] fix: 🐛 Sets pulse animation below badge component

---

NatDSSnapShotTests/Bar/SearchBar+Snapshot+Tests.swift
NatDSSnapShotTests/Bar/__Snapshots__/SearchBar+Snapshot+Tests/test_state_whenHasText_expectedCleanButtonIsVisible.1.png
Sources/Public/Components/Bar/SearchBar.swift

- Fixes search bar clear button

[DSY- 1514] fix: 🐛 Fixes search bar clear button

---

NatDS.podspec
NatDS.xcodeproj/project.pbxproj
SampleApp/NatDS-SampleApp.xcodeproj/project.pbxproj
SampleApp/Sources/Sample/Components/AppBar/AppBarDetailViewController.swift
SampleApp/Sources/Sample/Components/Iconography/IconographyItemViewController.swift
SampleApp/Sources/Sample/Components/NavigationDrawer/NavigationDrawerItemViewController.swift

From version `3.0.0` NatDS DOES NOT have ICONS anymore. From now on, icons must be added from [NatDSIcons](https://cocoapods.org/pods/NatDSIcons), a new library on Cocoapods.
- Bumps version to 3.0.0

[DSY-1750] Chore: Bump version to 3.0.0

---

Sources/Public/DesignTokens/NatSpacing.swift

- Add missing spacing token for public access: `.none`

Add missing public spacing token

---

Sources/Core/ViewStyling/Dialog/DialogStyle.swift
Sources/Public/Components/ValueText/ValueTextHighlight.swift

- Fix long title label for `NatDialog`
- Fix long description label for `Value Text Highlight`

[DSY-2050] Fix dialog and value text labels to accept long texts

---

NatDS.xcodeproj/project.pbxproj
NatDSSnapShotTests/TextField/TextField+Snapshot+Tests.swift
SampleApp/Sources/Sample/Components/Field/TextFieldItemViewController.swift
Sources/Public/Components/Field/Field.swift
Sources/Public/Components/Field/TextField+FeedbackState.swift
Sources/Public/Components/Field/TextField+InteractionState.swift
Sources/Public/Components/Field/TextField.swift
Sources/Public/Components/Field/TextFieldDelegate.swift
Sources/Public/Components/Field/TextFieldType.swift
TestHelpers/TextField/TextFieldDelegateMock.swift
Tests/Public/Components/Field/TextField+Types+Spec.swift
Tests/Public/Components/Field/TextFieldDelegateTests.swift

- Removes old delegate class `TextFieldDelegate` and replaces TextField's delegate with default `UITextFieldDelegate`
- Removes visibility icon on/off configuration for password type textfields, as it's a _pattern_ of use in the Design System's documentation
- Removes duplicated code moving style-related code to TextField's state enums

[DSY-2082] Refactor TextField

---

NatDS.xcodeproj/project.pbxproj
NatDSSnapShotTests/TextField/Field+Snapshot+Tests.swift
Sources/Public/Components/Field/NatField.swift
Sources/Public/Components/Field/TextField.swift

- Change old `Field` class name to `NatField`
This change was made to avoid conflicts when compiling with other libraries/modules that have classes also named `Field`.

Refactor: change Field class name to NatField

---

Sources/Public/Components/NavigationDrawer/NavigationDrawerItemCell.swift

- Fix `NatTag` visibility for reused cells at `NavigationDrawer`

Bugfix: Fix tag visibility for reused cells at navigation drawer

---

NatDS.xcodeproj/project.pbxproj
NatDSSnapShotTests/Counter/NatCounter+Snapshot+Tests.swift
Sources/Public/Components/Counter/NatCounter+Size.swift
Sources/Public/Components/Counter/NatCounter.swift
Sources/Public/Components/Counter/NatCounterButton.swift
Tests/Public/Components/Counter/NatCounter+Size+Spec.swift
Tests/Public/Components/Counter/NatCounter+Spec.swift

- Fixed bug that used to hide the corners of the `NatCounter` add and subtract buttons, at `iOS 11.4`
- Changed precision to the snapshot tests because of a [bug](https://github.com/pointfreeco/swift-snapshot-testing/issues/358) with the `SnapshotTesting` library

[DSY-2097] Fix visual bug at counter

---

Sources/Public/Components/Counter/NatCounter.swift
Tests/Public/Components/Counter/NatCounter+Spec.swift

- Refactor handler for `NatCounter` value change to be executed only if the value changes from an user input
- Add unit test cases for `NatCounter` value change scenarios

[DSY-2236] Fix bug at counter's value change handler

---

Sources/Core/Theme/SingleSourceOfTruth/BrandsThemes/Natura/NaturaDarkTheme.swift
Sources/Public/DesignTokens/NatFonts/NatFonts+TextStyle.swift
Sources/Public/DesignTokens/NatFonts/NatFonts.swift

- Fixed warning at `button` typography token caused by deprecation. This warning was blocking release to Cocoapods.

fix: update button typography token deprecation to fix cocoapods release

---

Sources/Public/Components/Field/TextField.swift

- Fix `textfield`'s helper text color when editing
- Fix `textfield`'s disabled state to remain disabled after updating text

[DSY-2276] Fix textfield bugs

---

Sources/Public/Components/Field/TextField.swift

- Fix bug that made `Text Field` look like 'active' when editing in 'error' state

[DSY-2427] Fix editing textfield with feedback state

---

Sources/Public/Components/ValueText/ValueTextHighlight.swift

- Deprecates `Value Text Highlight` component, which will no longer receive updates and fixes.

[DSY-2411] Deprecates value text highlight

---

Sources/Public/Components/Rating/NatRating+Style.swift
scripts/bump_version.sh

- Update script that sends NatDS to prod to allow deprecation warnings at Cocoapods

[DSY-2480] Fix send to prod script to allow deprecation

---

Sources/Public/Components/IconButton/NatIconButton.swift

- Update `Icon Button` action configuration method to prevent retain cycles
- Deprecate old action configuration method

[DSY-2490] Change icon button's action configuration to fix retain cycle

---

SampleApp/Sources/Sample/Components/AppBar/AppBarDataSource.swift
SampleApp/Sources/Sample/Components/AppBar/AppBarDetailViewController.swift
Sources/Public/Components/AppBar/AppBarContentType.swift
Sources/Public/Components/AppBar/UIViewController+Configure.swift
Tests/Public/Components/AppBar/UIViewController+Configure+Spec.swift

- Add method to set a `NatLogo` as the center view of the `App Bar Top` component (navigation bar).

[DSY-2241] Update AppBarTop with logo

---

Sources/Public/Components/AppBar/UIViewController+Configure.swift

- Deprecate method `configure(buttons: [UIBarButtonItem])` for `App Bar Top` configuration. It was replaced by the method `configure(appBarActionRight items: [UIView])`, which accepts any views and display them as buttons.

[DSY-2138] Deprecate old buttons config method at app bar top

---

SampleApp/Sources/Sample/Components/ExpansionPanel/ExpansionPanelViewController.swift
Sources/Public/Components/ExpansionPanel/ExpansionPanel.swift

- Add method to configure a custom animation at `Expansion Panel` opening and closing actions. This was necessary due to a bug with the closing animation, which can't be controlled by the Design System library because it depends on the app views' constraints.
- Update Sample App with example of custom animation at `Expansion Panel`.

[DSY-2401] Add custom animation configuration to expansion panel
